// Generated by `bun init`

declare namespace NodeJS {
  interface ProcessEnv {
    SUPABASE_URL: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    DATABASE_URL?: string;
    OPENAI_MODEL?: string;
    DOCS_UPLOAD_ROOT?: string;
    NODE_ENV?: "development" | "production" | "test";
  }
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
