CREATE TABLE IF NOT EXISTS course_results (
  id SERIAL PRIMARY KEY,
  no INTEGER NOT NULL,
  type VARCHAR(64) NOT NULL,
  name VARCHAR(2048) NOT NULL,
  specialty_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_course_results_no_type ON course_results (no, type);

CREATE TABLE IF NOT EXISTS courses(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL UNIQUE,
  teacher_id INTEGER,
  data JSONB,
  generated JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_topics(
  id SERIAL PRIMARY KEY,
  course_id INTEGER NOT NULL,
  index INTEGER NOT NULL,
  name VARCHAR(512) NOT NULL,
  lection TEXT NOT NULL,
  generated JSONB not null default '{}'::jsonb,
  data JSONB not null default '{}'::jsonb,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teachers(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL UNIQUE,
  email VARCHAR(256) UNIQUE,
  position VARCHAR(512),
  academic_title VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS templates(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL UNIQUE,
  file VARCHAR(512) NOT NULL,
  data JSONB not null default '{}'::jsonb,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompts(
  id SERIAL PRIMARY KEY,
  index INTEGER NOT NULL,
  type VARCHAR(64) NOT NULL,
  field VARCHAR(512) NOT NULL,
  system_prompt TEXT NOT NULL,
  prompt TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_prompts_index_type ON prompts (index, type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_prompts_field_type ON prompts (field, type);

CREATE TABLE IF NOT EXISTS specialties(
  id SERIAL PRIMARY KEY,
  code VARCHAR(64),
  name VARCHAR(512) NOT NULL UNIQUE,
  area_code VARCHAR(64),
  area VARCHAR(512) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);