CREATE TABLE IF NOT EXISTS course_results (
  id SERIAL PRIMARY KEY,
  name VARCHAR(2048) NOT NULL,
  type VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL UNIQUE,
  teacher_id INTEGER,
  data JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_lections(
  id SERIAL PRIMARY KEY,
  course_id INTEGER NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teachers(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);